language: c
compiler: gcc
script: make
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gstreamer0.10-plugins-base gstreamer0.10-plugins-good gstreamer0.10-plugins-bad-multiverse gstreamer0.10-plugins-ugly